name: Keep Repo Alive

permissions:
  contents: write

on:
  schedule:
    - cron: '0 3 5 * *'
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Empty Commit Keep Alive
        run: |
          git config --global user.name "AutoBot"
          git config --global user.email "autobot@github.com"
          git commit --allow-empty -m "Auto Renew Activity $(date +%Y-%m-%d)"
          git push
